---
framework: mocha
preRun:
     command:
        - yarn install
        - yarn run pretest
preMerge:
  pattern:
    - "./test/agenda.js"
postMerge:
  pattern:
    - "./test/agenda.js"
postRun:
     command:
        - yarn --version
version: 1.0
