---
framework: "mocha"
blocklist:
  - "test/agenda.js##unique##should demonstrate unique contraint##should modify one job when unique matches"
  - "test/find-and-lock-next-job.js##find-and-lock-next-job##should find jobs without lockedAt property"
  - "test/find-and-lock-next-job.js##find-and-lock-next-job##should find and rerun stuck jobs (with long ago lockedAt property)"
postMerge:
  pattern:
    - "./test/*.js"
preMerge:
  pattern:
    - "./test/*.js"
preRun:
  - npm install
postRun:
  - node --version
version: 2.0
