framework: mocha
tier: large
postMerge:
  pattern:
    - "./test/*.js"
preMerge:
  pattern:
    - "./test/*.js"
preRun:
     command:
        - npm install
postRun:
     command:
        - node --version
version: 1.0
