framework: mocha
tier: large
postMerge:
  pattern:
    - "./test/*.js"
  env:
    CI: true
preMerge:
  pattern:
    - "./test/*.js"
  env:
    CI: true
preRun:
     command:
        - yarn install
postRun:
     command:
        - yarn --version
configFile: "mocharc.yml"
version: 1.0
